### ISSUE TITLE
some errors when roslaunch the launch file

### ISSUE THREAD

**Issue by sushiye** [uzh-rpg/mh_autotune#1] opened 2021-04-02 02:08 UTC
hello, i have built  this project successfully but when i roslaunch  flightmare.launch, some errors appear as  figures bellow. could you give me some advice to solve them?
![2021-04-02 10-06-59 的屏幕截图](https://user-images.githubusercontent.com/71302949/113372410-3dbde080-939b-11eb-8728-2177ba3a11dd.png)
![2021-04-02 10-07-57 的屏幕截图](https://user-images.githubusercontent.com/71302949/113372449-53cba100-939b-11eb-8158-15bf0121a822.png)

**Comment by antonilo** [comment] 2021-04-07 16:52
@AlessandroSaviolo please have a look!

**Comment by AlessandroSaviolo** [comment] 2021-04-22 13:05
Hi sushiye! Sorry for the late reply. Are you still experiencing this error? If so, I can try to reproduce and solve it in the next few days. Let me know!

**Comment by sushiye** [comment] 2021-04-22 13:50
@AlessandroSaviolo Hi, I still have this error.  Thanks for your reply and I'll be waiting for your solution!

**Comment by junwoo091400** [comment] 2021-07-23 13:17
Getting same error, investigating the reason now
![image](https://user-images.githubusercontent.com/23277211/126787292-d04a6a70-0a25-4b08-a7b1-54f471e2038b.png)

**Comment by junwoo091400** [comment] 2021-07-23 14:36
Should be fixed by #6, please check @sushiye :+1:

**Closed as completed** 2021-08-30 16:37 UTC
